pandoc -f docbook -t asciidoc api.xml -o api.txt

[[overview]]
RESTful "Restaurant vote" API
-----------------------------

[![Codacy Badge](https://api.codacy.com/project/badge/grade/0aa43bd345364fab8d455f04e367fe0c)](https://www.codacy.com/app/javawebinar/topjava06)

ifdef::badges[]
image:https://api.codacy.com/project/badge/grade/0aa43bd345364fab8d455f04e367fe0c["", link="https://www.codacy.com/app/javawebinar/topjava06]
endif::[]

Maven/ Spring/ JPA(Hibernate)/ Spring MVC/ REST(Jackson)/ JUnit/ Spring rest docs.

### <a href="api-guide.html">API Documentation (generated by SPRING REST DOCS)</a>

## The task is:
Design and implement a JSON API using Hibernate/Spring/SpringMVC without frontend.

    Build a voting system for deciding where to have lunch.
    - 2 types of users: admin and regular users
    - Admin can input a restaurant and it's lunch menu of the day (2-5 items usually, just a dish name and price)
    - Menu changes each day (admins do the updates)
    - Users can vote on which restaurant they want to have lunch at
    - Only one vote counted per user
    - If user votes again the same day:
    - If it is before 11:00 we asume that he changed his mind.
    - If it is after 11:00 then it is too late, vote can't be changed

    Each restaurant provides new menu each day.

    P.S.: Asume that your API will used by a frontend developer to build frontend on top of that.



[[overview]]
Overview
--------

[[overview-http-verbs]]
HTTP verbs
~~~~~~~~~~

RESTful notes tries to adhere as closely as possible to standard HTTP
and REST conventions in its use of HTTP verbs.

[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Verb |Usage
|`GET` |Used to retrieve a resource
|`POST` |Used to create a new resource
|`PATCH` |Used to update an existing resource, including partial updates
|`DELETE` |Used to delete an existing resource
|=======================================================================

[[overview-http-status-codes]]
HTTP status codes
~~~~~~~~~~~~~~~~~

RESTful notes tries to adhere as closely as possible to standard HTTP
and REST conventions in its use of HTTP status codes.

[width="100%",cols="50%,50%",options="header",]
|=======================================================================
|Status code |Usage
|`200 OK` |The request completed successfully

|`201 Created` |A new resource has been created successfully. The
resource’s URI is available from the response’s `Location` header

|`204 No Content` |An update to an existing resource has been applied
successfully

|`400 Bad Request` |The request was malformed. The response body will
include an error providing further information

|`404 Not Found` |The requested resource did not exist
|=======================================================================

[[overview-errors]]
Errors
~~~~~~

Whenever an error response (status code >= 400) is returned, the body
will contain a JSON object that describes the problem. The error object
has the following structure:

Unresolved directive in api-guide.adoc -
include::E:\Java\Project\restaurantvote\target/generated-snippets/error-example/response-fields.adoc[]

For example, a request that attempts to apply a non-existent tag to a
note will produce a `400 Bad Request` response:

Unresolved directive in api-guide.adoc -
include::E:\Java\Project\restaurantvote\target/generated-snippets/error-example/http-response.adoc[]

[[overview-hypermedia]]
Hypermedia
~~~~~~~~~~

RESTful Notes uses hypermedia and resources include links to other
resources in their responses. Responses are in
http://stateless.co/hal_specification.html[Hypertext Application from
resource to resource. Language (HAL)] format. Links can be found beneath
the `_links` key. Users of the API should not create URIs themselves,
instead they should use the above-described links to navigate

[[resources]]
Resources
---------

[[resources-notes]]
Restaurants
~~~~~~~~~~~

The Notes resources is used to create and list notes

[[test-create-with-location]]
Creating a restaurant
^^^^^^^^^^^^^^^^^^^^^

A `POST` request is used to cratee a restaurant

[[_request_structure]]
Request structure
+++++++++++++++++

[width="100%",cols="34%,33%,33%",options="header",]
|====================================
|Path |Type |Description
|name |String |Name of the restaurant
|====================================

[[_example_request]]
Example request
+++++++++++++++

[source,bash]
----
$ curl 'http://localhost:8080/rest/admin/restaurants/' -i -X POST -H 'Content-Type: application/json;charset=UTF-8' -d '{
  "name" : "Шотиииииии"
}'
----

[[_example_response]]
Example response
++++++++++++++++

[source,http]
----
HTTP/1.1 201 Created
Location: http://localhost:8080/rest/admin/restaurants/100029
Content-Type: application/json;charset=UTF-8
Content-Length: 57

{
  "id" : 100029,
  "name" : "Шотиииииии"
}
----
